### ISSUE TITLE
Add reverse conversion features so I can convert all my existing regular expressions to JSVerbalExpressions format.

### ISSUE THREAD

**Issue by ahmadalibaloch** [VerbalExpressions/JSVerbalExpressions#96] opened 2016-01-05 08:09 UTC
It will be easy to have all my regular expressions in one format. For that I will need to convert existing regular expressions to this format. thanks.

**Comment by jehna** [comment] 2016-01-05 09:25
Duplicate of #80, closing this one.

**Closed by jehna** 2016-01-05 09:25 UTC
Labels: duplicate
