### ISSUE TITLE
anythingBut() and new lines

### ISSUE THREAD

**Issue by dtitov** [VerbalExpressions/JSVerbalExpressions#161] opened 2017-08-14 22:39 UTC
Not sure whether it's a bug or not, but if we build and expression from the [example](https://github.com/VerbalExpressions/JSVerbalExpressions) 
```
var tester = VerEx()
    .startOfLine()
    .then('http')
    .maybe('s')
    .then('://')
    .maybe('www.')
    .anythingBut(' ')
    .endOfLine();
```
then the output regex (which is actually `/^(http)(s)?(\:\/\/)(www\.)?([^\ ]*)$/gm` and not `/^(http)(s)?(\:\/\/)(www\.)?([^\ ]*)$/` as in example - there are `g` and `m` at the end) will go wrong for the next input:
```
test
https://github.com/VerbalExpressions/JSVerbalExpressions
test
https://github.com/VerbalExpressions/JSVerbalExpressions
123 https://codepen.io/flesler/pen/AEIFc 123
```

Proof: https://regex101.com/r/FuyIoN/2

AFAIU, that's because `anythingBut(' ')` output (`/(?:[^ ]*)/`) matches literally anything, **including new line character**. So it will capture whole this part:
```
https://github.com/VerbalExpressions/JSVerbalExpressions
test
https://github.com/VerbalExpressions/JSVerbalExpressions
```

Well, one may say that it's logical and one can manually add `\n` into `anythingBut(' ')` to get `anythingBut(' \n')`, **but this does not compile to a regex**: we get 
```
/^(?:http)(?:s)?(?:\:\/\/)(?:www\.)?(?:[^ 
]*)$/gm
```
instead of
```
/^(?:http)(?:s)?(?:\:\/\/)(?:www\.)?(?:[^ \n]*)$/gm
```

**Comment by dtitov** [comment] 2017-08-17 09:31
Any thoughts?

**Comment by mrGrochowski** [comment] 2017-10-16 12:56
bump

**Comment by jehna** [comment] 2017-10-17 06:35
> there are `g` and `m` at the end

> AFAIU, that's because `anythingBut(' ')` output `(/(?:[^ ]*)/)` matches literally anything, including new line character.

The flags `gm` are by design, as the library expects no previous knowledge of regular expressions: Including that normal regular expressions are not multiline or global by default. Therefore `anythingBut` makes sense in its literal form.

> Well, one may say that it's logical and one can manually add `\n` into `anythingBut(' ')` to get 
`anythingBut(' \n')`, but this does not compile to a regex

It _does_ compile to valid regular expression. Your example works just as intended:
```js
const tester = VerEx().startOfLine().then('http').maybe('s').then('://').maybe('www.').anythingBut(' \n').endOfLine();

const testee = `test
https://github.com/VerbalExpressions/JSVerbalExpressions
test
https://github.com/VerbalExpressions/JSVerbalExpressions
123 https://codepen.io/flesler/pen/AEIFc 123`

tester.exec(testee) // prints "https://github.com/VerbalExpressions/JSVerbalExpressions" at char 5
tester.exec(testee) // prints "https://github.com/VerbalExpressions/JSVerbalExpressions" at char 67
```

So as you see, this works just fine. Yes, the output of the regular expression is a bit funny:
```js
/^(?:http)(?:s)?(?:\:\/\/)(?:www\.)?(?:[^ 
]*)$/gm
```

but you can get the newline by compiling a normal regular expression too:
```js
new RegExp('hello\nworld')
/* prints:
/hello
world/
*/
```

Closing this issue, because there doesn't seem to be any issue here. If I'm wrong, please comment to this issue with more details and I can reopen it and have a closer look

**Closed** 2017-10-17 06:36 UTC
