### ISSUE TITLE
Dart port

### ISSUE THREAD

**Issue by Ne4istb** [VerbalExpressions/JSVerbalExpressions#97] opened 2016-01-05 08:14 UTC
I'm working on Dart port, could you create a repo for this, please?

**Comment by ionutvmi** [comment] 2016-01-05 21:32
https://github.com/VerbalExpressions/DartVerbalExpressions

Please let me know if you need more permissions for that repo.

**Comment by ionutvmi** [comment] 2016-01-15 13:50
closing this as the access seems to work fine,

**Closed by ionutvmi** 2016-01-15 13:50 UTC

**Comment by Ne4istb** [comment] 2016-01-16 16:57
@ionutvmi Thanks, access works fine, but, for some reasons, https://api.github.com/orgs/VerbalExpressions/repos (used in verbalExpressions.github.io) does not return this repo in the list. Could it be some specific option in repository or organization settings?

**Comment by ionutvmi** [comment] 2016-01-16 19:48
@Ne4istb good catch.
It was caused by the github api pagination. By default is 30.
Should be fixed now.

**Comment by Ne4istb** [comment] 2016-01-16 20:42
@ionutvmi Thanks
